CHANGELOG.md
helm/cilium/templates/hubble-relay/podsecuritypolicy.yaml

This PR:
- adds missing PSP for hubble-relay

Add PSP for hubble-relay.

---

CHANGELOG.md
helm/cilium/files/policies/egress.yaml
helm/cilium/files/policies/ingress.yaml
helm/cilium/templates/default-policies/configmap.yaml
helm/cilium/templates/default-policies/job.yaml
helm/cilium/templates/default-policies/rbac.yaml
helm/cilium/templates/default-policies/serviceaccount.yaml
helm/cilium/values.yaml

We currently rely on `cluster-resources-app` to create `Cilium` network policies.
I believe it is cleaner and easier to use if we bundle the creation of such policies in the cilium app itself.
With this PR I added a new job, similar to the one we have for cert-manager for a similar use case, that creates the policies after cilium CRDs are created.
The feature is disabled by default to be backward compatible.

Add creation of default Policies with a job to the helm chart

---

CHANGELOG.md
helm/cilium/templates/hubble-relay/podsecuritypolicy.yaml

This PR:
- updates the PSP for hubble to allow it to mount secrets as a volume

Added missing volume type to hubble psp

---

CHANGELOG.md
helm/cilium/templates/default-policies/job.yaml

This PR:
Adds the create-default-policies Job as a post-upgrade hook.
The hook doesn't seem to work in the first place, I suspect because the app-operator is doing an upgrade.
In any case it seems like this is a good idea as it will update the default policies if they change.
**(haven't changed)**

Run default-policies job also post-upgrade

---

CHANGELOG.md
helm/cilium/templates/default-policies/job.yaml
helm/cilium/templates/default-policies/podsecuritypolicy.yaml

Based on kube-scheduler timing,  it might be that the job that creates default policies runs too late, when cilium network policies are already in place.
This means that the job's calls to the api-server are blocked because there are no policies to allow them.
This PR runs the job in hostNetwork to avoid this chicken-egg problem.

Default policies improve

---

CHANGELOG.md
helm/cilium/files/policies/egress.yaml

In legacy WCs, we used to have a restrict-all default network policy for pods in `giantswarm` and `kube-system` namespaces: https://github.com/giantswarm/k8scloudconfig/blob/master/files/k8s-resource/network_policies.yaml
Currently, we ship an "allow all egress" policy as part of cilium installation that breaks behavior compatibility in legacy cluster.
This PR deletes such policy as it's wrong.
This meant that all apps needed to ship their own NetworkPolicy in order to access in-cluster resources such as the api-server.
We used to create such policies using an ipBlock selector like here for example: https://github.com/giantswarm/cert-manager-app/blob/master/helm/cert-manager-app/templates/cainjector-np.yaml#L24
Unfortunately, the ipBlock selector does not work on cilium for in-cluster …

Restrict default egress

---

CHANGELOG.md
helm/cilium/templates/cilium-agent/daemonset.yaml
helm/cilium/values.yaml

When switching from aws-cni/kube-proxy to cilium in kube-proxy mode, we need to cleanup iptables rules before running cilium, otherwise services end up being broken (see https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#quick-start )
This PR:
- adds a new initContainer, disabled by default and added through an helm variable, that cleans up iptables rules before starting cilium agent.

Cleanup iptables

---

CHANGELOG.md
helm/cilium/templates/cilium-agent/daemonset.yaml

- Run `cleanup-kube-proxy-iptables` container in cilium agent in privileved mode
- Use iptables-nft binaries for `cleanup-kube-proxy-iptables` container.

Fix kube-proxy cleanup init container

---

CHANGELOG.md
helm/cilium/values.yaml

This PR:
- bumped default version to latest v1.11 patch (v1.11.9)  
This is required for compatibility with Ubuntu 22.04 (see https://github.com/kubernetes-sigs/kubespray/issues/9039#issuecomment-1199904978 for details)

Bumped cilium to v1.11.9

---

CHANGELOG.md
helm/cilium/templates/cilium-agent/service.yaml
helm/cilium/templates/cilium-operator/service.yaml
helm/cilium/templates/hubble-relay/networkpolicy.yaml
helm/cilium/values.yaml

This PR:
- Enables hubble
- Enables operator monitoring
Prometheus scraping is not directly enabled in this application as it would make it depend on ServiceMonitor CRD being installed before the CNI.
https://github.com/giantswarm/cilium-servicemonitors-app was created to provide the ServiceMonitors to be scraped by the Observability Bundle's Prometheus agent.

Enable Monitoring and Hubble

---

CHANGELOG.md
helm/cilium/templates/cilium-agent/daemonset.yaml
helm/cilium/templates/cilium-nodeinit/daemonset.yaml
helm/cilium/templates/cilium-operator/_helpers.tpl
helm/cilium/templates/cilium-preflight/daemonset.yaml
helm/cilium/templates/cilium-preflight/deployment.yaml
helm/cilium/templates/clustermesh-apiserver/deployment.yaml
helm/cilium/templates/clustermesh-apiserver/tls-cronjob/_job-spec.tpl
helm/cilium/templates/etcd-operator/cilium-etcd-operator-deployment.yaml
helm/cilium/templates/hubble-relay/deployment.yaml
helm/cilium/templates/hubble-ui/deployment.yaml
helm/cilium/templates/hubble/tls-cronjob/_job-spec.tpl
helm/cilium/values.schema.json
helm/cilium/values.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/26243
This PR:
- Use `image.registry` value as image registry for all containers in the chart

Use `image.registry` value as image registry for all containers in the chart

---

CHANGELOG.md
helm/cilium/templates/hubble-ui/networkpolicy.yaml

When exposing hubble ui through ingress (disabled by default) other pods (ingress controller in this case) need to be able to connect to the hubble UI pod.
Since cilium is installed in kube-system, by default all ingress traffic towards pods is blocked, hence we need a networkpolicy to enable traffic.
This PR:
- does what I wrote above

Add network policy to allow exposing hubble UI through ingress.

---

CHANGELOG.md
helm/cilium/values.schema.json
helm/cilium/values.yaml

This PR:
- Increased Policy BPF Max map to 65536 from 16384.
- Enabled cilium_bpf_map_pressure metric.
- Excluding PSS labels from cilium identities/policies.
- Excluding Flux labels from cilium identities/policies.
- Excluding Helm labels from cilium identities/policies.
- Excluding job specific labels from cilium identities/policies.

Improvements

---

CHANGELOG.md
helm/cilium/templates/extra-policies/configmap.yaml
helm/cilium/templates/extra-policies/job.yaml
helm/cilium/templates/extra-policies/podsecuritypolicy.yaml
helm/cilium/templates/extra-policies/rbac.yaml
helm/cilium/templates/extra-policies/serviceaccount.yaml
helm/cilium/values.schema.json
helm/cilium/values.yaml

Supersedes https://github.com/giantswarm/cluster-aws/pull/341 – it didn't fit in `cluster-aws` since we need to want to be able to install the policies in MCs and WCs that have a proxy.
This PR adds a way to allow traffic to DNS and, in case of proxy-private clusters, to the proxy host via L7 network policies.
The `Job` and related resources were copied from the `default-policies` solution and not added on top since the "default" aren't very configurable and I didn't want to mess with those. They are also not well-commented and therefore a candidate for removal or changes.
Tested like this:
- [n/a] upgrade from previous version works

Support creating `CiliumNetworkPolicy` manifests that allow egress requests to DNS and proxy hosts

---

CHANGELOG.md
helm/cilium/templates/default-policies/podsecuritypolicy.yaml

Towards https://github.com/giantswarm/roadmap/issues/2533
This PR:
- adds the `capabilities check` for rendering psp to the `default-policies job`

Add missing capabilities check for PSP on default-policies installer job

---

CHANGELOG.md
helm/cilium/templates/default-policies/configmap.yaml
helm/cilium/templates/default-policies/job.yaml
helm/cilium/templates/default-policies/podsecuritypolicy.yaml
helm/cilium/templates/default-policies/rbac.yaml
helm/cilium/templates/default-policies/serviceaccount.yaml
helm/cilium/values.schema.json
helm/cilium/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/27266
As discussed in the issue, we don't need the so-called default-policies' allow rules anymore, given how all operators were instrumented with their own, minimal network policies (`giantswarm` + `kube-system` namespaces).
Tested by upgrading on a fresh CAPA MC. The policies are gone and operator logs still show no problems.

Support removal of previously-deployed default policies by setting `defaultPolicies.enabled=false` and `defaultPolicies.remove=false`

---

CHANGELOG.md
helm/cilium/templates/extra-policies/configmap.yaml

Towards https://github.com/giantswarm/roadmap/issues/3155

Replace `ToServices`/`ToPorts` combination in CiliumNetworkPolicy because of breakage in Cilium v1.14

---

CHANGELOG.md
helm/cilium/values.yaml
vendir.lock.yml
vendir.yml

SocketLB for pods are causing issues with connected UDP. In effect,
restarting our DNS servers breaks resolution on those apps that rely on
it.
We need this in place until https://github.com/cilium/cilium/issues/28820 is sorted out.

Use SocketLB on host NS only.

---

CHANGELOG.md
helm/cilium/values.yaml
vendir.lock.yml

This PR:
- add safe-to-evicts annotations, to allow clusterautoscaler to evict pods on deployments with only 1 replica.
Towards https://github.com/giantswarm/giantswarm/issues/29883

Add safe-to-evict annotations to Hubble Relay and UI

---

CHANGELOG.md
Makefile.custom.mk
README.md
helm/cilium/README.md
helm/cilium/values.schema.json
helm/cilium/values.yaml
helm/cilium/values.yaml.tmpl
vendir.lock.yml

This PR:
- adds a helm values schema file
Tested this on capa, capz, capv and capvcd using the cluster test suites available in their respective repositories:
- capa Works (test failed because of some other error)
- capz Works
- capv Works
- capvcd Works (test failed because of some other error)
https://github.com/giantswarm/giantswarm/issues/29542

Add helm schema via vendir sync

---

helm/cilium/values.yaml
renovate.json5

- ignore upstream chart
- Revert "Update ghcr.io/spiffe/spire-server Docker tag to v1.9.2 (#169)"
- Revert "Update ghcr.io/spiffe/spire-agent Docker tag to v1.9.2 (#168)"
This PR:

Ignore updates in chart directory

---

CHANGELOG.md
helm/cilium/templates/extra-policies/configmap.yaml
helm/cilium/templates/extra-policies/job.yaml
helm/cilium/templates/extra-policies/podsecuritypolicy.yaml
helm/cilium/templates/extra-policies/rbac.yaml
helm/cilium/templates/extra-policies/serviceaccount.yaml
helm/cilium/values.schema.json
helm/cilium/values.yaml
helm/cilium/values.yaml.tmpl
vendir.lock.yml

This PR:
- Enables the deletion of the extra-policies resources created by a job.
The idea is that setting `extraPolicies.remove` as `true` and `extraPolicies.allowEgressTo*.enabled` as `false`; the job deletes the previously created network policies. This has to be used in combination with the network-policies-app to ensure no disruption.
Towards https://github.com/giantswarm/roadmap/issues/3261

Enable deletion of extra network policies in job

---

CHANGELOG.md
helm/cilium/templates/cilium-cni-configmap.yaml

Towards https://github.com/giantswarm/roadmap/issues/2563
For the full feature, I'm adding the correct security group and subnet selection, as we have in Vintage AWS.

Cilium ENI mode for CAPA

---

helm/cilium/Chart.yaml

This PR:
- adds this repo's URL to the Chart metadata. We need this in Backstage context to understand which GitHub repo this app originates from.
Context: https://github.com/giantswarm/roadmap/issues/3291

Add app repo URL to sources in Chart.yaml

---

CHANGELOG.md
helm/cilium/Chart.yaml
helm/cilium/README.md
helm/cilium/templates/cilium-preflight/daemonset.yaml
helm/cilium/templates/hubble-ui/deployment.yaml
helm/cilium/values.yaml
vendir.lock.yml

This PR:
- Updates to upstream [v1.15.6](https://github.com/cilium/cilium/releases/tag/v1.15.6)
Tested to be working in:
- [CAPZ](https://github.com/giantswarm/cluster-azure/pull/291#issuecomment-2165593833)
- [CAPV](https://github.com/giantswarm/cluster-vsphere/pull/219#issuecomment-2165559935)
- [CAPA](https://github.com/giantswarm/cluster-aws/pull/656#issuecomment-2175753925)
- [CAPVCD](https://github.com/giantswarm/cluster-cloud-director/pull/321#issuecomment-2176032646)

Update chart to upstream v1.15.6

---

CHANGELOG.md
helm/cilium/README.md
helm/cilium/values.yaml
helm/cilium/values.yaml.tmpl
vendir.lock.yml

This PR restores the changed `policyMapMax` value back to `65536` instead of upstream default `16384`. This was first changed in https://github.com/giantswarm/cilium-app/pull/80 and changed back to upstream default in https://github.com/giantswarm/cilium-app/pull/146/

Fix policyMapMax regression

---

CHANGELOG.md
diffs/helm__cilium__templates__cilium-agent__service.yaml.patch
helm/cilium/templates/cilium-agent/service.yaml
sync/patches/metrics_port/README.md
sync/patches/metrics_port/cilium_agent__service.yaml.patch
sync/patches/metrics_port/patch.sh
sync/sync.sh

This PR:
- Restore agent metrics
Towards https://github.com/giantswarm/giantswarm/issues/33501
---

 Re-enable agent metrics port

---

CHANGELOG.md
diffs/helm__cilium__values.yaml.tmpl.patch
helm/cilium/README.md
helm/cilium/values.schema.json
helm/cilium/values.yaml
helm/cilium/values.yaml.tmpl
sync/patches/values/values.yaml.tmpl
tests/e2e/.gitignore

This PR:
- Adds resource requests and limits to Hubble UI and Relay
- Adds resource requests and limits to Cilium Operator
Towards https://github.com/giantswarm/giantswarm/issues/31475 and https://github.com/giantswarm/giantswarm/issues/31747
---

Add resource requests and limits to Hubble and Cilium Operator

---

CHANGELOG.md
diffs/helm__cilium__values.yaml.tmpl.patch
helm/cilium/README.md
helm/cilium/values.yaml
helm/cilium/values.yaml.tmpl
sync/patches/values/values.yaml.tmpl

This PR:
- Enable ctAccounting by default
From 1.16, Conntrack accounting was disabled by default. This brings back the behavior of previous versions.
Unfortunately this can't be enabled in 1.16, so we enable it by default from 1.17 on.
---

Enable ctAccounting by default

---

CHANGELOG.md
diffs/helm__cilium__values.yaml.tmpl.patch
helm/cilium/README.md
helm/cilium/values.yaml
helm/cilium/values.yaml.tmpl
sync/patches/values/values.yaml.tmpl
sync/sync.sh
vendir.yml

This PR:
- Increase Cilium opreator resource limits
- Also add entries to changelog from previous PR.
- Print Upstream CHANGELOG as well at the end of the sync to be able to incorporate some into ours
---

Increase Cilium operator resource limits.

---

CHANGELOG.md
helm/cilium/templates/_helpers.tpl
sync/patches/k8sservicehost_auto/README.md
sync/patches/k8sservicehost_auto/_helpers.tpl.patch
sync/patches/k8sservicehost_auto/patch.sh
sync/sync.sh

This PR:
In some edge-case scenarios, the chart gets installed before kubeadm has had the chance to populate the cluster-info ConfigMap. In such cases the chart gets installed with "auto" as the k8s service host and cilium fails to start. This doesn't get remediated automatically. With this change, if "auto" is provided as values, the chart will fail to get installed if it can't find the cluster-info ConfigMap, and the installer will be forced to retry the chart installation.
---

Improve the k8s service host autodiscovery mechanism
