giantswarm/cilium-app

CHANGELOG.md, helm/cilium/templates/hubble-relay/podsecuritypolicy.yaml
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
This PR:
=> Fix typo in PSP

CHANGELOG.md, helm/cilium/Chart.yaml
This PR:
- aligns helm chart ownership and CODEOWNERS file
Otherwise, it triggers some alerts
=> Align helm chart ownership and CODEOWNERS file

helm/cilium/templates/hubble-ui/podsecuritypolicy.yaml
=> Add Hubble UI PSP

CHANGELOG.md, helm/cilium/templates/hubble-relay/networkpolicy.yaml, helm/cilium/templates/hubble-ui/networkpolicy.yaml
=> Switch to ciliumnetworkpolicies

CHANGELOG.md, helm/cilium/templates/hubble-relay/networkpolicy.yaml, helm/cilium/templates/hubble-ui/networkpolicy.yaml
=> revert to np

CHANGELOG.md, helm/cilium/values.schema.json, helm/cilium/values.yaml
This PR:
- Reenables BPF metrics
=> Enable BFP metrics

CHANGELOG.md, helm/cilium/templates/cilium-agent/podsecuritypolicy.yaml, helm/cilium/templates/cilium-operator/podsecuritypolicy.yaml, helm/cilium/templates/default-policies/podsecuritypolicy.yaml, helm/cilium/templates/extra-policies/podsecuritypolicy.yaml, helm/cilium/templates/hubble-relay/podsecuritypolicy.yaml, helm/cilium/templates/hubble-ui/podsecuritypolicy.yaml, helm/cilium/values.schema.json, helm/cilium/values.yaml
Issue: https://github.com/giantswarm/giantswarm/issues/28345
This PR:
=> Replace PSP installation condition

CHANGELOG.md, helm/cilium/templates/cilium-cni-configmap.yaml, helm/cilium/values.schema.json, helm/cilium/values.yaml
add cilium ENI support for EKS
towards https://github.com/giantswarm/giantswarm/issues/28553
=> cilium-eni-eks

CHANGELOG.md, helm/cilium/values.yaml
=> Disable uninstalling the CNI config and binary when the agent goes down.

.github/pull_request_template.md
To avoid people manually changing this app, I added a note to the PR template.
=> Add note about app generation in PR template

helm/cilium/templates/default-policies/job.yaml, helm/cilium/templates/extra-policies/job.yaml
override hardcoded quay registry for policy jobs
=> Cilium policy jobs - remove hardcoded container image registry for cilium jobs

CHANGELOG.md, helm/cilium/Chart.yaml
=> Cilium Handover

CHANGELOG.md, helm/cilium/Chart.yaml, helm/cilium/README.md, helm/cilium/templates/cilium-agent/daemonset.yaml, helm/cilium/templates/cilium-configmap.yaml, helm/cilium/templates/cilium-envoy/daemonset.yaml, helm/cilium/templates/clustermesh-apiserver/deployment.yaml, helm/cilium/values.schema.json, helm/cilium/values.yaml, helm/cilium/values.yaml.tmpl, vendir.lock.yml
Update from upstream v1.15.4
Tested in 
- https://github.com/giantswarm/cluster-aws/pull/598
- https://github.com/giantswarm/cluster-azure/pull/260
- https://github.com/giantswarm/cluster-vsphere/pull/184
=> Upgrade from update-from-upstream-v1.15.4

CHANGELOG.md, helm/cilium/Chart.yaml, helm/cilium/README.md, helm/cilium/templates/cilium-agent/daemonset.yaml, helm/cilium/templates/cilium-configmap.yaml, helm/cilium/templates/cilium-envoy/daemonset.yaml, helm/cilium/templates/cilium-nodeinit/daemonset.yaml, helm/cilium/values.schema.json, helm/cilium/values.yaml, helm/cilium/values.yaml.tmpl, vendir.lock.yml
This PR updates the app to cilium [v1.15.5](https://github.com/cilium/cilium/releases/tag/v1.15.5)
Tested in:
- https://github.com/giantswarm/cluster-aws/pull/598
- https://github.com/giantswarm/cluster-azure/pull/281
- https://github.com/giantswarm/cluster-vsphere/pull/205
=> Sync changes for v1.15.5

CHANGELOG.md, diffs/helm__cilium__values.yaml.tmpl.patch, helm/cilium/README.md, helm/cilium/values.schema.json, helm/cilium/values.yaml, helm/cilium/values.yaml.tmpl, sync/patches/values/values.yaml.tmpl
This PR:
- patch values for hubble relay
- patch values for hubble ui
- patch values for cilium-operator
Towards https://github.com/giantswarm/giantswarm/issues/31167 https://github.com/giantswarm/giantswarm/issues/31172 https://github.com/giantswarm/giantswarm/issues/31171
=> Patch values for policy rules violation

renovate.json5
Changes in this PR will change how Renovate create update PRs to trigger e2e tests
=> Make Renovate trigger e2e tests

CHANGELOG.md, diffs/helm__cilium__values.yaml.tmpl.patch, helm/cilium/README.md, helm/cilium/values.yaml, helm/cilium/values.yaml.tmpl, sync/patches/values/values.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/31507
---
=> Enable Envoy Proxy in standalone DaemonSet.

CHANGELOG.md
This PR:
- _Adds/changes/fixes/removes ..._
---
=> Update CHANGELOG with latest patch release

CHANGELOG.md
This PR updates the changelog on `main` to include 0.31.2
=> Add release v0.31.2 to Changelog

.github/workflows/zz_generated.create_release.yaml
This PR tries to verify assumptions mentioned in https://github.com/giantswarm/giantswarm/issues/32877
=> Create long lived release branch from parent version

CHANGELOG.md
This Pr updates the changelog with release 0.31.3
/skip-ci changelog only
=> Add 0.31.3 to changelog

CHANGELOG.md
Just add v0.31.4 to the Changelog on main
=> Add 0.31.4 to changelog on main

tests/e2e/go.mod
This PR:
- _Adds/changes/fixes/removes ..._
---
=> update go in e2e tests

renovate.json5
This PR:
- _Adds/changes/fixes/removes ..._
---
=> Group deps from E2E tests
